# Generated by Django 5.2.3 on 2025-07-29 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setupsystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=40)),
                ('bus_name', models.CharField(default='company bus new', max_length=20)),
                ('bus_seat_num', models.PositiveIntegerField(default=1)),
                ('bus_status', models.CharField(choices=[('RN', 'Running'), ('DW', 'Down')], default='Running')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus List',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=45)),
                ('is_default', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=85, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(blank=True, max_length=45, null=True)),
                ('surname', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Customer's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('middlename', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('booking_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_pass', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Number of passengers')),
                ('payment_due', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=20, null=True)),
                ('book_modified', models.DateTimeField(auto_now_add=True)),
                ('book_created_at', models.DateTimeField(auto_now=True)),
                ('feedback_resolved', models.BooleanField(default=False)),
                ('booked_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setupsystem.route')),
                ('destination_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_to', to='setupsystem.location', verbose_name='To')),
                ('location_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from', to='setupsystem.location', verbose_name='From')),
                ('bus_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.busdetail')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_phonenumber', models.CharField(max_length=18, verbose_name="Driver's Phone Number")),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setupsystem.location')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Driver's Name")),
                ('known_routes', models.ManyToManyField(blank=True, related_name='known_routes', to='setupsystem.route')),
            ],
        ),
        migrations.AddField(
            model_name='busdetail',
            name='bus_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.driver'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=16)),
                ('payment_deadline', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.booking')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('seats_booked', models.PositiveIntegerField(default=0)),
                ('trip_departure_date', models.CharField(blank=True, max_length=20)),
                ('trip_departure_time', models.CharField(blank=True, max_length=20)),
                ('trip_fare', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('bus_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.busdetail')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setupsystem.route')),
            ],
            options={
                'verbose_name': 'Scheduled Trip',
                'verbose_name_plural': 'Scheduled Trips',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.trip'),
        ),
    ]
