# Generated by Django 5.2.3 on 2025-06-22 17:29

import aktcUI.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DepartureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='00')),
                ('minute', models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default='00')),
                ('meridian', models.CharField(choices=[('AM', 'am'), ('PM', 'pm')], default='am')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('local_government', models.CharField(max_length=45)),
                ('bus_stop', models.CharField(max_length=30)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.departuretime')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_phonenumber', models.CharField(max_length=18, verbose_name="Driver's Phone Number")),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Driver's Name")),
            ],
        ),
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=40)),
                ('bus_name', models.CharField(default='aktc company bus new', max_length=20)),
                ('bus_status', models.CharField(choices=[('RN', 'Running'), ('DW', 'down')], default='Running')),
                ('bus_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bus_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.busdetail')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.customer')),
                ('departure_time', models.ManyToManyField(related_name='departure_time', to='aktcUI.dailyscheduletime')),
                ('destination_to', models.ManyToManyField(related_name='location_from', to='aktcUI.location', verbose_name='To')),
                ('location_from', models.ManyToManyField(related_name='location_to', to='aktcUI.location', verbose_name='From')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDaysSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_or_only_date', models.DateField(default=datetime.datetime(2025, 6, 22, 17, 29, 23, 717861, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date')),
                ('end_date', models.DateField(blank=True, null=True, unique=True)),
                ('daily_schedule', models.ForeignKey(default='8', on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.dailyscheduletime')),
            ],
        ),
    ]
