# Generated by Django 5.2.3 on 2025-08-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0002_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport'),
        ),
    ]
