# Generated by Django 5.2.3 on 2025-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0003_alter_driver_passport'),
        ('setupsystem', '0005_location_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='known_routes',
            field=models.ManyToManyField(blank=True, null=True, related_name='known_routes', to='setupsystem.route'),
        ),
    ]
