# Generated by Django 5.2.3 on 2025-06-22 17:35

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0003_alter_departuretime_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyscheduletime',
            name='time',
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 17, 35, 47, 494001, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
        migrations.AddField(
            model_name='dailyscheduletime',
            name='time',
            field=models.ManyToManyField(related_name='daily_schedule_time', to='aktcUI.departuretime'),
        ),
    ]
