# Generated by Django 5.2.3 on 2025-06-22 19:30

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0004_remove_dailyscheduletime_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookticket',
            name='departure_time',
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 19, 29, 38, 332691, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='departure_time',
            field=models.CharField(default='2', max_length=45),
            preserve_default=False,
        ),
    ]
