# Generated by Django 5.2.3 on 2025-08-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0006_alter_driver_known_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetail',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.bus'),
        ),
        migrations.AlterField(
            model_name='busdetail',
            name='bus_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.driver'),
        ),
    ]
