# Generated by Django 5.2.3 on 2025-06-22 22:31

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0006_alter_weekdaysschedule_start_or_only_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='departure_time',
            field=models.CharField(choices=[]),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 22, 22, 31, 19, 187039, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
