# Generated by Django 5.2.3 on 2025-06-23 09:08

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0007_alter_bookticket_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 10, 7, 59, 811139)),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 9, 7, 59, 811139, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
