# Generated by Django 5.2.3 on 2025-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0008_alter_driver_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
    ]
