# Generated by Django 5.2.3 on 2025-06-23 09:14

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0008_bookticket_email_bookticket_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.customer'),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 10, 13, 24, 281168)),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='departure_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='email',
            field=models.EmailField(default='camelion@farmland.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 9, 13, 24, 280169, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
