# Generated by Django 5.2.3 on 2025-06-23 09:23

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0009_alter_bookticket_client_alter_bookticket_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 10, 23, 19, 753194)),
        ),
        migrations.RemoveField(
            model_name='bookticket',
            name='destination_to',
        ),
        migrations.RemoveField(
            model_name='bookticket',
            name='location_from',
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 9, 23, 19, 752199, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='destination_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_to', to='aktcUI.location', verbose_name='To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookticket',
            name='location_from',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_from', to='aktcUI.location', verbose_name='From'),
            preserve_default=False,
        ),
    ]
