# Generated by Django 5.2.3 on 2025-06-23 09:28

import aktcUI.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0010_alter_bookticket_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookticket',
            name='departure_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 9, 27, 50, 196762, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
