# Generated by Django 5.2.3 on 2025-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0011_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(blank=True, default='TRIP-20250806000000AM218-73FFB', editable=False, max_length=40, unique=True),
        ),
    ]
