# Generated by Django 5.2.3 on 2025-06-23 09:38

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0013_alter_weekdaysschedule_start_or_only_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=40)),
                ('bus_name', models.CharField(default='aktc company bus new', max_length=20)),
                ('bus_status', models.CharField(choices=[('RN', 'Running'), ('DW', 'down')], default='Running')),
            ],
        ),
        migrations.RemoveField(
            model_name='busdetail',
            name='bus_name',
        ),
        migrations.RemoveField(
            model_name='busdetail',
            name='bus_status',
        ),
        migrations.RemoveField(
            model_name='busdetail',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 9, 38, 44, 154056, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
        migrations.AddField(
            model_name='busdetail',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.bus'),
        ),
    ]
