# Generated by Django 5.2.3 on 2025-06-23 09:43

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0014_bus_remove_busdetail_bus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='bus_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.busdetail'),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 9, 43, 6, 61290, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
