# Generated by Django 5.2.3 on 2025-06-23 13:06

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0015_alter_bookticket_bus_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookticket',
            old_name='username',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='bookticket',
            name='middlename',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='surname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='busdetail',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.bus'),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 13, 4, 49, 206124, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
