# Generated by Django 5.2.3 on 2025-06-23 13:33

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0016_rename_username_bookticket_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customer',
            name='middlename',
            field=models.CharField(default='middle', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(default='surname', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 13, 32, 47, 589698, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
