# Generated by Django 5.2.3 on 2025-08-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0019_alter_trip_trip_id'),
        ('setupsystem', '0006_alter_weekdaysschedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setupsystem.route'),
        ),
    ]
