# Generated by Django 5.2.3 on 2025-08-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0020_alter_trip_route'),
        ('setupsystem', '0006_alter_weekdaysschedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setupsystem.route'),
        ),
    ]
