# Generated by Django 5.2.3 on 2025-06-25 09:14

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0020_alter_weekdaysschedule_start_or_only_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='number_of_travellers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 25, 9, 14, 10, 248073, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
