# Generated by Django 5.2.3 on 2025-07-01 15:04

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0021_bookticket_number_of_travellers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_seat_num',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 15, 4, 40, 305999, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
