# Generated by Django 5.2.3 on 2025-07-01 16:07

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0022_bus_bus_seat_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('reference', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(default='company bus new', max_length=20),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 1, 16, 7, 32, 137282, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=45, null=True)),
                ('middlename', models.CharField(blank=True, max_length=45, null=True)),
                ('surname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('departure_time', models.CharField(max_length=100)),
                ('seats_booked', models.IntegerField(default=1)),
                ('book_modified', models.DateTimeField(auto_now_add=True)),
                ('book_created', models.DateTimeField(auto_now=True)),
                ('bus_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.busdetail')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.customer')),
                ('destination_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_to', to='aktcUI.location', verbose_name='To')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_from', to='aktcUI.location', verbose_name='From')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trip_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('payment_date', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Success', 'success'), ('Failed', 'failed')], max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.booking')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.paymentmethod')),
            ],
        ),
        migrations.DeleteModel(
            name='BookTicket',
        ),
    ]
