# Generated by Django 5.2.3 on 2025-07-02 14:33

import aktcUI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0026_booking_payment_due_payment_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='departure_date',
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 2, 14, 32, 55, 552991, tzinfo=datetime.timezone.utc), unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
