# Generated by Django 5.2.3 on 2025-07-04 13:26

import aktcUI.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0029_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_of_pass',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of passengers'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.location'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus_detail',
            field=models.ForeignKey(default='Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='aktcUI.busdetail'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_seat_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
        migrations.CreateModel(
            name='PreviousSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_or_only_date', models.DateField(unique=True, verbose_name='Start/Only date')),
                ('daily_schedule', models.ForeignKey(default='8', on_delete=django.db.models.deletion.DO_NOTHING, to='aktcUI.dailyscheduletime')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.PositiveIntegerField(default=2000)),
                ('journey_average_length', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('add_reverse', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='aktcUI.location')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_destination', to='aktcUI.location')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='known_routes',
            field=models.ManyToManyField(blank=True, related_name='known_routes', to='aktcUI.route'),
        ),
        migrations.AddField(
            model_name='weekdaysschedule',
            name='trip_route',
            field=models.ManyToManyField(related_name='trip_route', to='aktcUI.route'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('seats_booked', models.PositiveIntegerField(default=0)),
                ('trip_departure_date', models.CharField(blank=True, max_length=20)),
                ('trip_departure_time', models.CharField(blank=True, max_length=20)),
                ('trip_fare', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending')),
                ('bus_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.busdetail')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktcUI.route')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.trip'),
        ),
    ]
