# Generated by Django 5.2.3 on 2025-07-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0030_review_remove_booking_seats_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_route',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='aktcUI.route'),
        ),
    ]
