# Generated by Django 5.2.3 on 2025-07-07 13:24

import aktcUI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0035_alter_weekdaysschedule_start_or_only_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(unique=True, validators=[aktcUI.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
