# Generated by Django 5.2.3 on 2025-07-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0036_alter_weekdaysschedule_start_or_only_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
