# Generated by Django 5.2.3 on 2025-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0037_booking_feedback_resolved_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
