# Generated by Django 5.2.3 on 2025-07-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0038_rename_firstname_booking_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='surname',
            new_name='last_name',
        ),
    ]
