# Generated by Django 5.2.3 on 2025-07-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0039_rename_surname_booking_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='customer',
        ),
    ]
