# Generated by Django 5.2.3 on 2025-07-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0040_rename_client_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_route',
            field=models.ForeignKey(blank=True, default='23', null=True, on_delete=django.db.models.deletion.CASCADE, to='aktcUI.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus_detail',
            field=models.ForeignKey(blank=True, default='Deleted', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='aktcUI.busdetail'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=20, null=True),
        ),
    ]
