# Generated by Django 5.2.3 on 2025-07-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0041_alter_booking_booked_route_alter_booking_bus_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_to', to='aktcUI.location', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_from', to='aktcUI.location', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_pass',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Number of passengers'),
        ),
    ]
