# Generated by Django 5.2.3 on 2025-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0042_alter_booking_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
