# Generated by Django 5.2.3 on 2025-07-10 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0043_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bus_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.busdetail'),
        ),
    ]
