# Generated by Django 5.2.3 on 2025-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0045_alter_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktcUI.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_to', to='aktcUI.location', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from', to='aktcUI.location', verbose_name='From'),
        ),
    ]
