# Generated by Django 5.2.3 on 2025-07-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0046_alter_booking_booked_route_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='book_created',
            new_name='book_created_at',
        ),
    ]
