# Generated by Django 5.2.3 on 2025-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0048_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='payment_deadline',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_title',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
