# Generated by Django 5.2.3 on 2025-07-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0049_rename_payment_date_payment_payment_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='method_title',
            new_name='title',
        ),
    ]
