# Generated by Django 5.2.3 on 2025-07-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktcUI', '0050_rename_method_title_paymentmethod_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='method',
        ),
    ]
