# Generated by Django 5.2.3 on 2025-07-29 11:34

import datetime
import django.db.models.deletion
import setupsystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='00')),
                ('minute', models.CharField(choices=[('00', '00'), ('05', '05'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default='00')),
                ('meridian', models.CharField(choices=[('AM', 'am'), ('PM', 'pm')], default='am')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('local_government', models.CharField(max_length=45)),
                ('bus_stop', models.CharField(max_length=30)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.ManyToManyField(related_name='daily_schedule_time', to='setupsystem.departuretime')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_or_only_date', models.DateField(unique=True, verbose_name='Start/Only date')),
                ('daily_schedule', models.ForeignKey(default='8', on_delete=django.db.models.deletion.DO_NOTHING, to='setupsystem.dailyscheduletime')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.PositiveIntegerField(default=2000)),
                ('journey_average_length', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('add_reverse', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='setupsystem.location')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_destination', to='setupsystem.location')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDaysSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_or_only_date', models.DateField(unique=True, validators=[setupsystem.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date')),
                ('end_date', models.DateField(blank=True, null=True, unique=True)),
                ('daily_schedule', models.ForeignKey(default='8', on_delete=django.db.models.deletion.DO_NOTHING, to='setupsystem.dailyscheduletime')),
                ('trip_route', models.ManyToManyField(related_name='trip_route', to='setupsystem.route')),
            ],
            options={
                'verbose_name': 'Week day Schedule',
                'verbose_name_plural': 'Week day Schedule',
            },
        ),
    ]
