# Generated by Django 5.2.3 on 2025-07-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setupsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyscheduletime',
            options={'verbose_name': 'Daily Schedule (Time)', 'verbose_name_plural': 'Daily Schedule (Multiple Departure Times per day)'},
        ),
        migrations.AlterModelOptions(
            name='departuretime',
            options={'verbose_name': 'Departure Time (hour of day)', 'verbose_name_plural': 'Departure Time (hour of day)'},
        ),
    ]
