# Generated by Django 5.2.3 on 2025-08-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupsystem', '0002_alter_dailyscheduletime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location/'),
        ),
    ]
