# Generated by Django 5.2.3 on 2025-08-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupsystem', '0003_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
