# Generated by Django 5.2.3 on 2025-08-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupsystem', '0004_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
