# Generated by Django 5.2.3 on 2025-08-05 17:01

import setupsystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupsystem', '0005_location_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekdaysschedule',
            name='start_or_only_date',
            field=models.DateField(validators=[setupsystem.models.WeekDaysSchedule.validate_start_date], verbose_name='Start/Only date'),
        ),
    ]
